<?php if($erreur!=''): ?><div class="alert alert-danger" role="alert"><?=$erreur?></div><?php endif;?>
<?php if(isset($values['id'])):?>
	<form action="editArticle.php" method="POST" enctype="multipart/form-data">
	<input type="hidden" name="id" value="<?=$values['id']?>">
<?php else:?>
	<form action="addArticle.php" method="POST" enctype="multipart/form-data">
<?php endif;?>
	<div class="form-group row">
		<label for="titre" class="col-sm-2 col-form-label">Titre :</label>
		<div class="col-sm-10">
			<input class="form-control" type="text" value="<?=$values['titre']?>" name="titre" id="titre">
		</div>
    </div>
    <div class="form-group  row">
		<label for="content" class="col-sm-2 col-form-label">Contenu :</label>
		<div class="col-sm-10">
			<textarea class="form-control" name="content" id="content"><?=$values['content']?></textarea>
		</div>
	</div>
	<div class="form-group row">
		<label for="date" class="col-sm-2 col-form-label">Date de publication :</label>
		<div class="col-sm-10">
			<input class="form-control" type="date" value="<?=$values['date']?>" name="date" id="date">
		</div>
    </div>
	<div class="form-group  row">
		<label for="picture" class="col-sm-2 col-form-label">Image d'entete :</label>
		<div class="col-sm-10">
			<input class="form-control" type="file" value="" name="picture" id="picture">
		</div>
		<?php if(isset($values['picture']) && $values['picture'] != NULL):?>
			<img width="70" src="<?=URL_BLOG.REP_UPLOAD.'/articles/'.$values['picture']?>">
		<?php endif;?>

    </div>
    <div class="form-check  row">
		<label for="publish" class="col-sm-2 col-form-label">Publier :</label>
		<input type="checkbox" name="publish" id="publish" value="1">
	</div>
	
    <h2>Catégories :</h2>
    <?php foreach( $categories as $categorie):?>
        <div class="form-check row">
            <label class="col-sm-2 col-form-label" for="cat<?= $categorie['cat_title']; ?>"><?= $categorie['cat_title']; ?></label>
            <input type="checkbox" name="categories[]" id="cat<?= $categorie['cat_title']; ?>" value="<?= $categorie['cat_id']; ?>">
        </div>
    <?php endforeach;?>
	
	<input type="submit" value="Enregistrer" class="btn btn-default">
	<input type="reset" value="Réinitialiser" class="btn btn-default">
</form>

  <script>
    tinymce.init({
    selector: 'textarea',
    height: 500,
    menubar: false,
    plugins: [
        'advlist autolink lists link image charmap print preview anchor textcolor',
        'searchreplace visualblocks code fullscreen',
        'insertdatetime media table contextmenu paste code help wordcount'
    ],
    toolbar: 'insert | undo redo |  formatselect | bold italic backcolor  | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help',
    content_css: [
        '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
        '//www.tinymce.com/css/codepen.min.css']
    });
  </script>

