<?php if($erreur!=''): ?><div class="alert alert-danger" role="alert"><?=$erreur?></div><?php endif;?>
<?php if(isset($values['id'])):?>
	<form action="editUser.php" method="POST" enctype="multipart/form-data">
	<input type="hidden" name="id" value="<?=$values['id']?>">
<?php else:?>
	<form action="addUser.php" method="POST" enctype="multipart/form-data">
<?php endif;?>
	<div class="form-group row">
		<label for="nom" class="col-sm-2 col-form-label">Nom :</label>
		<div class="col-sm-10">
			<input class="form-control" type="text" value="<?=$values['nom']?>" name="nom" id="nom">
		</div>
	</div>
	<div class="form-group row">
		<label for="prenom" class="col-sm-2 col-form-label">Prénom :</label>
		<div class="col-sm-10">
			<input class="form-control" type="text" value="<?=$values['prenom']?>" name="prenom" id="prenom">
		</div>
	</div>
	<div class="form-group  row">
		<label for="email" class="col-sm-2 col-form-label">Email :</label>
		<div class="col-sm-10">
			<input class="form-control" type="email" value="<?=$values['email']?>" name="email" id="email">
		</div>
	</div>
	<div class="form-group  row">
		<label for="password" class="col-sm-2 col-form-label">Mot de passe :</label>
		<div class="col-sm-4">
			<input class="form-control" type="password" value="" name="password" id="password">
		</div>
		
		<label for="passwordConf" class="col-sm-2 col-form-label">Confirmez :</label>
		<div class="col-sm-4">
			<input class="form-control" type="password" value="" name="passwordConf" id="passwordConf">
		</div>
	</div>
	<div class="form-group  row">
		<label for="bio" class="col-sm-2 col-form-label">Bio :</label>
		<div class="col-sm-10">
			<textarea class="form-control" name="bio" id="bio"><?=$values['bio']?></textarea>
		</div>
	</div>
	<div class="form-group  row">
		<label for="avatar" class="col-sm-2 col-form-label">Avatar :</label>
		<div class="col-sm-10">
			<input class="form-control" type="file" value="" name="avatar" id="avatar">
		</div>
		<?php if(isset($values['avatar']) && $values['avatar'] != NULL):?>
			<img width="70" src="<?=URL_BLOG.REP_UPLOAD.'/users/'.$values['avatar']?>">
		<?php endif;?>

	</div>
	<div class="form-group  row">
		<label for="role" class="col-sm-2 col-form-label">Rôle :</label>
		<div class="col-sm-10">
			<select class="form-control" name="role">
				<option value="ROLE_ADMIN" <?=($values['role']=='ROLE_ADMIN')?'selected':''?>>Admin</option>
				<option value="ROLE_AUTHOR" <?=($values['role']=='ROLE_AUTHOR')?'selected':''?>>Auteur</option>
			</select>
		</div>
	</div>
	<input type="submit" value="Enregistrer" class="btn btn-default">
	<input type="reset" value="Réinitialiser" class="btn btn-default">
</form>

