<section class="table-responsive">
    <table id="tableDonnee" class="table">
        <thead>
            <th>Nom</th>
            <th>Prenom</th>
            <th>Email</th>
            <th>Avatar</th>
            <th>Rôle</th>
            <th></th>
        </thead>
        <tbody>
            <?php foreach($users as $user):?>
                <tr>
                    <td><?=$user['user_lastname']?></td>
                    <td><?=$user['user_firstname']?></td>
                    <td><a href="mailto:<?=$user['user_email']?>"><?=$user['user_email']?></a></td>
                    <td><img width="70" src="<?=URL_BLOG.REP_UPLOAD.'users/'.$user['user_avatar']?>"></td>
                    <td><?=$user['user_role']?></td>
                    <td><a href="editUser.php?id=<?=$user['user_id']?>"><i class="fas fa-edit"></i></a> <a href="delUser.php?id=<?=$user['user_id']?>" data-toggle="modal" data-target="#delete"><i class="fas fa-trash-alt"></i></a></td>
                </tr> 
            <?php endforeach;?>
        </tbody>
    </table>
</section>