<!DOCTYPE html>
<html lang="fr">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?=$title?></title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!--Datatable -->
    <link href="http://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css
" rel="stylesheet">

  </head>

  <body>

    <!-- Page Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h1 class="mt-5"><?=$title?></h1>
		  	<?php if($erreur!=''): ?><div class="alert alert-danger" role="alert"><?=$erreur?></div><?php endif;?>
			<form role="form" action="login.php" method="POST">
				<fieldset>
					<div class="form-group">
						<input class="form-control" placeholder="E-mail" name="email" type="email" autofocus>
					</div>
					<div class="form-group">
						<input class="form-control" placeholder="Password" name="password" type="password" value="">
					</div>
					<div class="checkbox">
						<label>
							<input name="remember" type="checkbox" value="Remember Me">Se souvenir de moi
						</label>
					</div>
					<input type="submit" value="Login">
				</fieldset>
			</form>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="http://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    

  </body>

</html>



 