<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Module 10 - Portfolio</title>
	<!-- Appel CSS -->
	<link rel="stylesheet" href="css/font-awesome.min.css">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bree+Serif">
	<link rel="stylesheet" href="css/normalize.css">
	<link rel="stylesheet" href="css/style.css">
</head>
<body>
	<!--HEADER-->
	<header class="container">
		<a href="index.php"><img src="img/logo.svg" alt="logo de mon portfolio" /> John Doe</a>
		<nav>
			<a href="index.php"><i class="fa fa-home"></i> Accueil</a>
			<a href="#resume"><i class="fa fa-folder-open"></i> Articles</a>
			<a href="#contact"><i class="fa fa-envelope"></i> Contact</a>
		</nav>
	</header>
	<!--MAIN CONTENT-->
	<section id="presentation">
		<div class="container">
			<h1>Bonjour et bienvenue sur mon blog</h1>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
			<a class="cta" href="#">Découvrez-moi !</a>
		</div>
	</section>
	<main class="container">
		<section id="resume">
			<?php
            include('tpl/'.$vue.'.phtml');
			?>
		</section>
		<section id="contact">
			<h2>Contactez-moi</h2>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
			<form>
				<input type="text" name="name" placeholder="Votre prénom">
				<input type="text" name="mail" placeholder="Votre mail">
				<textarea name="message" rows="1" placeholder="Votre message"></textarea>
				<button type="submit" name="button">Envoyer</button>
				<button type="reset" name="button">Effacer</button>
			</form>
		</section>
	</main>
	<small id="licence">
	    <a rel="license" href="https://3wa.fr/propriete-materiel-pedagogique/"><img alt="Propriété de la 3W Academy" style="border-width:0" src="https://3wa.fr/wp-content/themes/3wa2015/img/logos/big.png" /></a><br /><span>Cet exercice</span> de <a href="https://3wa.fr">3W Academy</a> est mis à disposition <a rel="license" href="https://3wa.fr/propriete-materiel-pedagogique/">pour l'usage personnel des étudiants, Pas de Rediffusion - Attribution - Pas d'Utilisation Commerciale - Pas de Modification - International</a>.<br />Les autorisations au-delà du champ de cette licence peuvent être obtenues auprès de <a href="mailto:contact@3wa.fr" rel="cc:morePermissions">contact@3wa.fr</a>. Les maquettes ont été réalisées par <a href="http://www.justine-muller.fr">Justine Muller</a>.
	</small>
</body>
</html>
